SET C51INC=C:\Keil\C51\INC\DCD\;C:\Keil\C51\INC\
SET C51LIB=C:\Keil\C51\LIB
SET CPU_TYPE=DQ8051
SET CPU_VENDOR=Digital Core Design
SET UV2_TARGET=DoCD
SET CPU_XTAL=0x02FAF080
C:\Keil\C51\BIN\C51.EXE @docd.__i
C:\Keil\C51\BIN\C51.EXE @ir_nec.__i
C:\Keil\C51\BIN\C51.EXE @Int_Vec.__i
C:\Keil\C51\BIN\C51.EXE @SunReg.__i
C:\Keil\C51\BIN\A51.EXE @startup._ia
C:\Keil\C51\BIN\A51.EXE @showhex._ia
C:\Keil\C51\BIN\BL51.EXE @Q628.lnp
